source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "f5b6a5cf-fbdf-4a9f-b3b8-3c2cd00225a4"
  client_secret                     = "0e760437-bf34-4aad-9f8d-870be799c55d"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "East Asia"
  managed_image_name                = "linuxWordpressPackerImage"
  managed_image_resource_group_name = "linuxwordpresspacker-rg"
  os_type                           = "Linux"
  subscription_id                   = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
  tenant_id                         = "72f988bf-86f1-41af-91ab-2d7cd011db47"
  vm_size                           = "Standard_B1s"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  
  provisioner "shell" {
    scripts = [
      # base install
      "linux_config_script.sh"
    ]
  }
  provisioner "file" {
    source = "nginx.conf"
    destination = "~/nginx.conf"
  }
  provisioner "file" {
    source = "wordpress_nginx.conf"
    destination = "~/wordpress_nginx.conf"
  }
  provisioner "file" {
    source = "wordpress_phpfpm.conf"
    destination = "~/phppool.conf"
  }
  provisioner "file" {
    source = "php-fpm.conf"
    destination = "~/php-fpm.conf"
  }
  provisioner "file" {
    source = "php.ini"
    destination = "~/php.ini"
  }
  provisioner "file" {
    source = "monitrc"
    destination = "~/monitrc"
  }
  provisioner "file" {
    source = "monitd_mphhopackertest.conf"
    destination = "~/monitd_mphhopackertest.conf"
  }
  provisioner "shell" {
    scripts = [
      # second stage of linux setup
      "linux_config_script_pt2.sh"
    ]
  }
  provisioner "shell" {
    scripts = [
      # final WordPress application setup
      "wordpress_site_setup.sh"
    ]
  }

}
